//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tFX_tool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquityTable
    {
        public int Id { get; set; }
        public string EquityORAmountinvested { get; set; }
        public string Maxlotsize { get; set; }
        public string Pipvalue { get; set; }
        public string ProfitORLoss { get; set; }
    }
}
